# Generated by Django 3.1.1 on 2022-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221101_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Enter 10 digits phone number', max_length=12, unique=True, verbose_name='Phone Number'),
        ),
    ]
