# Generated by Django 3.1.1 on 2022-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221104_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Enter 12 digits start with 2547...', max_length=12, unique=True, verbose_name='Phone Number'),
        ),
    ]
